services:
  mongo:
    image: mongo:6
    container_name: quran-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db
  flask-app:
    build:
      context: .
      dockerfile: docker/flask.dockerfile
    container_name: quran-api
    restart: unless-stopped
    ports:
      - 6000:5000
    volumes:
      - ./rag/uploads:/app/uploads
    depends_on:
      - mongo
    environment:
      - PYTHONUNBUFFERED=1
