services:
  flask:
    build:
      context: .
      dockerfile: docker/flask.dockerfile
    container_name: quran-api
    ports:
      - 6000:5000
    volumes:
      - ./rag/uploads:/app/uploads
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/
  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db
